config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  # ログインページ
  controller :sessions do
    get 'login', action: :new
    get 'logout', action: :destroy
    get 'auth/:provider/callback', action: :create
  end

  # マイページ
  resource :mypage, controller: :users,
                    only: %i[show edit update destroy]

  # 全プロジェクト
  resources :projects, only: %i[index show] do
    resources :columns, only: %i[new create edit update destroy] do
      get 'previous', on: :member
      get 'next', on: :member
      resources :cards, only: %i[new create edit update destroy] do
        get 'previous', on: :member
        get 'next', on: :member
      end
    end

    # 招待
    controller :invitations do
      get 'invite', action: :invite
      get 'generate_invitaions', action: :generate_invitaions
      resources :invitations, only: %i[create]
    end

    # 参加
    resources :participations, only: %i[create]

    # 情報
    get 'info', to: 'projects#info'

    # ログ
    resources :logs, only: %i[index]
  end

  # マイプロジェクト
  resources :myprojects, controller: :projects, module: :myprojects,
                         only: %i[index new create edit update destroy]

  # お知らせ
  resources :notifications, only: %i[index]
end

app/models/user.rb
class User < ApplicationRecord
  include RemoteFileAttachable

  has_many :owner_projects, class_name: 'Project', foreign_key: :owner_id,
                            dependent: :destroy
  has_many :assigned_cards, class_name: 'Card', foreign_key: :assignee_id,
                            dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :invitation_projects, through: :invitations, source: :project
  has_many :participations, dependent: :destroy
  has_many :member_projects, through: :participations, source: :project

  has_one_attached :image

  attribute :new_image
  attr_reader :login_message

  validates :name, presence: true
  validates :provider, presence: true
  validates :uid, presence: true, uniqueness: { scope: :provider }
  validates :new_image, file_size: { maximum: MAX_IMAGE_SIZE },
                        file_type: { in: ALLOWED_IMAGE_TYPES },
                        if: :new_image

  after_find :set_find_message
  after_create :set_create_message

  # 新しい画像のバリデーションが成功した場合に、更新時に画像添付する
  before_update :attach_new_image

  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]

    find_or_create_by(provider: provider, uid: uid) do |user|
      user.name = auth[:info][:name]
      user.attach_remote_file!(auth[:info][:image])
    end
  end

  scope :search, ->(keyword) do
    where('name LIKE ?', "%#{sanitize_sql_like(keyword)}%")
  end

  def owner?(project)
    project.owner_id == id
  end

  def invited?(project)
    project.invitations.exists?(user_id: id)
  end

  def notifications_count
    invitations.count
  end

  def participate_in(project)
    participations.build(project: project).save
  end

  def member?(project)
    participations.exists?(project_id: project.id)
  end

  # include RemoteFileAttachable
  def attachment_target
    image
  end

  private

  attr_writer :login_message

  def set_find_message
    self.login_message = 'ログインしました'
  end

  def set_create_message
    self.login_message = 'アカウント登録しました'
  end

  def attach_new_image
    image.attach(new_image) if new_image
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: 'アカウント情報を更新しました'
    else
      render :edit
    end
  end

  def destroy
    manager = DeregistrationManager.new(@user)
    manager.destroy_user!
    reset_session
    redirect_to login_path, notice: '退会が完了しました。ユーザーを削除しました。'
  end

  private

  def user_params
    params.require(:user).permit(:name, :new_image)
  end

  def set_user
    @user = current_user
  end
end

app/views/users/_form.html.slim
= form_with model: user, url: mypage_path, local: true do |f|

  = f.text_field :name, placeholder: '名前を入力', class: field_class(model: user, field: :name)
  = render 'shared/form_errors', model: user, field: :name

  = f.label :new_image, class: user.filefield_label_class, for: 'js-filefield'
    #js-filename.mb-0 画像の変更
  = f.file_field :new_image, id: 'js-filefield', class: 'd-none', accept: 'image/jpeg,image/jpg,image/png, image/gif'
  = render 'shared/form_errors', model: user, field: :new_image

  = f.submit '更新', class: 'btn btn-lg btn-block btn-secondary bg-light-purple border-middle-purple text-middle-purple mt-2 mt-lg-3 mb-lg-4'

app/views/users/edit.html.slim
.row.align-items-center.mt-100px

  - if @user.image.attached?
    .col-md-4.ml-auto.text-center.col-lg-3
      = image_tag @user.image, class: 'size255x255 rounded-circle img-fluid mb-4', id: 'js-image'

  .col-md-5.mr-auto.col-lg-4.ml-lg-5
    = render 'users/form', user: @user

= javascript_pack_tag 'mypage'

app/views/users/show.html.slim
.row.align-items-center.mt-100px

  - if @user.image.attached?
    .col-md-4.ml-auto.text-center.col-lg-3
      = image_tag @user.image, class: 'size255x255 rounded-circle img-fluid mb-4'

  .col-md-5.mr-auto.col-lg-4.ml-lg-5
    h3.text-purple  = @user.name
  
    = link_to 'ユーザ情報の編集', edit_mypage_path, class: 'btn btn-lg btn-block btn-secondary bg-light-purple border-middle-purple text-middle-purple mt-2 mt-lg-3 mb-lg-4'

    .row
      .col-8.pr-2
        = link_to 'ログアウト', logout_path, class: 'btn btn-lg btn-block btn-outline-secondary mt-5'

      .col-4.pl-0
        = link_to '退会', mypage_path, method: :delete, data: { confirm: 'ユーザーは削除されます。本当に退会しますか？' }, class: 'btn btn-lg btn-block btn-outline-secondary mt-5'