config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  # ログインページ
  controller :sessions do
    get 'login', action: :new
    get 'logout', action: :destroy
    get 'auth/:provider/callback', action: :create
  end

  # マイページ
  resource :mypage, controller: :users,
                    only: %i[show edit update destroy]

  # 全プロジェクト
  resources :projects, only: %i[index show] do
    resources :columns, only: %i[new create edit update destroy] do
      get 'previous', on: :member
      get 'next', on: :member
      resources :cards, only: %i[new create edit update destroy] do
        get 'previous', on: :member
        get 'next', on: :member
      end
    end

    # 招待
    controller :invitations do
      get 'invite', action: :invite
      get 'generate_invitaions', action: :generate_invitaions
      resources :invitations, only: %i[create]
    end

    # 参加
    resources :participations, only: %i[create]

    # 情報
    get 'info', to: 'projects#info'

    # ログ
    resources :logs, only: %i[index]
  end

  # マイプロジェクト
  resources :myprojects, controller: :projects, module: :myprojects,
                         only: %i[index new create edit update destroy]

  # お知らせ
  resources :notifications, only: %i[index]
end

app/views/shared/_flash.html.slim
- if flash
  - flash.each do |key, value|
    div class='#{flash_class(key)}' role='alert'
      = value
      button.close type='button' data-dismiss='alert' aria-label='Close'
        span aria-hidden='true'
          | &times;

app/views/shared/_footer.html.slim
footer.footer.bg-light-purple
  .container
    span.text-middle-purple ©2019 project_cards_tasks

app/views/shared/_form_errors.html.slim
- if model.errors[field].present?
  .invalid-feedback.d-block
    - model.errors[field].each do |msg|
      p.my-1
        = model.class.human_attribute_name(field)
        = msg

app/views/shared/_header.html.slim
header.header
  nav.navbar.navbar-expand-sm.navbar-dark.bg-purple
    .container
      button.navbar-toggler type='button' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'
        span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        ul.navbar-nav.mr-auto.mt-3.mt-sm-0
          li.nav-item
            = link_to '全プロジェクト', root_path, class: 'btn btn-outline-light'
          li.nav-item.mt-2.mt-sm-0.ml-0.ml-sm-2
            = link_to 'マイプロジェクト', myprojects_path, class: 'btn btn-outline-light'

        ul.navbar-nav.mt-3.mt-sm-0.ml-0.ml-sm-2
          - if logged_in?
            li.nav-item
              h5.my-0.my-sm-1
                = link_to current_user.notifications_count, notifications_path, class: 'badge badge-light'
            - if current_user.image.attached?
              li.nav-item.mt-2.mt-sm-0.ml-0.ml-sm-1.ml-md-3
                = link_to mypage_path do
                  = image_tag current_user.image, class: 'size35x35 rounded-circle'
          - else
            li.nav-item
              = link_to 'ログイン', login_path, class: 'btn btn-outline-light'