config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  # ログインページ
  controller :sessions do
    get 'login', action: :new
    get 'logout', action: :destroy
    get 'auth/:provider/callback', action: :create
  end

  # マイページ
  resource :mypage, controller: :users,
                    only: %i[show edit update destroy]

  # 全プロジェクト
  resources :projects, only: %i[index show] do
    resources :columns, only: %i[new create edit update destroy] do
      get 'previous', on: :member
      get 'next', on: :member
      resources :cards, only: %i[new create edit update destroy] do
        get 'previous', on: :member
        get 'next', on: :member
      end
    end

    # 招待
    controller :invitations do
      get 'invite', action: :invite
      get 'generate_invitaions', action: :generate_invitaions
      resources :invitations, only: %i[create]
    end

    # 参加
    resources :participations, only: %i[create]

    # 情報
    get 'info', to: 'projects#info'

    # ログ
    resources :logs, only: %i[index]
  end

  # マイプロジェクト
  resources :myprojects, controller: :projects, module: :myprojects,
                         only: %i[index new create edit update destroy]

  # お知らせ
  resources :notifications, only: %i[index]
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :columns, -> { order(position: :asc) }, dependent: :destroy
  has_many :cards, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :invitees, through: :invitations, source: :user
  has_many :participations, dependent: :destroy
  has_many :members, through: :participations, source: :user
  has_many :logs, dependent: :destroy
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id

  # プロジェクト一覧で1ページに表示するプロジェクトの個数
  COUNT_PER_PAGE = 9

  # プロジェクト一覧の先頭に挿入されるプロジェクト以外（リンクなど）の個数
  PADDING_COUNT = 1

  validates :name, presence: true, uniqueness: true, length: { maximum: 140 }
  validates :summary, length: { maximum: 300 }

  scope :for_full_list, ->(page) do
    order(id: :desc).page(page).per(COUNT_PER_PAGE)
  end

  scope :for_accessible_list, ->(user, page) do
    if page
      for_accessible_list_second_page_or_later(user, page)
    else
      for_accessible_list_first_page(user)
    end
  end

  scope :for_accessible_list_first_page, ->(user) do
    count_for_first_page = COUNT_PER_PAGE - PADDING_COUNT
    accessible(user).order(id: :desc).page(nil).per(count_for_first_page)
  end

  scope :for_accessible_list_second_page_or_later, ->(user, page) do
    # もし1ページ目が指定されても値を返さないようにする
    # （kaminariのissueによると、1ページ目でpaddingマイナス値を使うと不具合がある）
    return [] if ['1', 1, nil].include?(page)

    accessible(user).order(id: :desc).page(page).per(COUNT_PER_PAGE)
                    .padding(-PADDING_COUNT)
  end

  scope :accessible, ->(user) do
    owned_by(user).or(participated_in_by(user)).distinct
  end

  scope :owned_by, ->(user) do
    # .accessibleでorを使用できるようleft_joinsする
    left_joins(:participations).where(owner_id: user.id)
  end

  scope :participated_in_by, ->(user) do
    left_joins(:participations).where(participations: { user_id: user.id })
  end

  def accessible?(user)
    self.class.accessible(user).exists?(id)
  end

  def invite(user)
    invitations.build(user: user).save
  end

  def accessible_users
    [owner] + members
  end

  def set_owner!(new_owner)
    raise 'new_owner is not in members' unless members.exists?(new_owner.id)

    remove_member!(new_owner)
    update!(owner: new_owner)
  end

  def remove_member!(member)
    participations.find_by!(user: member).destroy!
  end

  def oldest_member
    members.order(created_at: :asc).first
  end
end

app/controllers/myprojects/projects_controller.rb
class Myprojects::ProjectsController < ApplicationController
  before_action :set_project, only: %i[edit update destroy]

  def index
    @projects = Project.for_accessible_list(current_user, params[:page])
    respond_to do |format|
      format.html
      format.js { render 'projects/index' }
    end
  end

  def new
    @project = current_user.owner_projects.build
  end

  def create
    @project = current_user.owner_projects.build(project_params)

    if @project.save
      redirect_to projects_path, notice: 'プロジェクトを作成しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path, notice: 'プロジェクトを更新しました'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy!
    redirect_to projects_path, notice: 'プロジェクトを削除しました'
  end

  private

  def project_params
    params.require(:project).permit(:name, :summary)
  end

  def set_project
    @project = current_user.owner_projects.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.for_full_list(params[:page])
  end

  def show
    @project = Project.accessible(current_user)
                      .includes(columns: :cards)
                      .find(params[:id])
  end

  def info
    @project = Project.accessible(current_user)
                      .includes(:owner)
                      .find(params[:project_id])
    @members = @project.members.order(id: :asc)
  end
end

app/views/projects/_card.html.slim
.card.border-middle-purple.bg-light-purple.text-middle-purple.my-2
  .card-body.overflow-scroll.pt-3.pb-2
    .row
      .col-2.px-0.my-auto
        = link_to previous_project_column_card_path(project, column, card), class: column.arrow_link_class(:left) do
          i.far.fa-arrow-alt-circle-left.fa-lg

      .col.text-center.text-truncate.px-0
        = link_to edit_project_column_card_path(project, column, card), class: 'link-unstyled' do
          .card.btn.btn-lg.btn-outline-secondary.bg-light-purple.text-middle-purple
            .card-body.text-truncate.p-0
              .card-text.h6 = card.name

      .col-2.text-right.px-0.my-auto
        = link_to next_project_column_card_path(project, column, card), class: column.arrow_link_class(:right) do
          i.far.fa-arrow-alt-circle-right.fa-lg

    .row.mt-2
      .col.text-right
        span.mr-1.align-bottom = card.due_date_text

        - if card.assignee.image.attached?  
          = image_tag card.assignee.image, class: 'size35x35 rounded-circle'

app/views/projects/_column.html.slim
.col-8.col-sm-6.col-md-5.col-lg-4.col-xl-3.col-scroll-x
  .card.border-middle-purple
    .card-header.bg-white-purple
      .row.align-items-center
        .col-2.pl-2.pr-0
          = link_to previous_project_column_path(project, column), class: column.arrow_link_class(:left) do
            i.fas.fa-arrow-circle-left.fa-lg

        .col.text-center.text-truncate.px-0
          = link_to edit_project_column_path(project, column), class: 'card btn btn-lg btn-outline-secondary bg-white-purple text-middle-purple' do
            .card-body.text-truncate.p-0
              .card-text = column.name

        .col-2.pl-0.pr-2.text-right
          = link_to next_project_column_path(project, column), class: column.arrow_link_class(:right) do
            i.fas.fa-arrow-circle-right.fa-lg

    .card-body
      - column.cards.each do |card|
        = render 'card', project: project, column: column, card: card

      = link_to 'カードを追加', new_project_column_card_path(project, column), class: 'btn btn-sm btn-outline-secondary border-middle-purple text-middle-purple my-2'

app/views/projects/_projects.html.slim
- projects.each do |project|
  .col-12.col-sm-6.col-lg-4.mt-4

    - if current_user.owner?(project)
      a.link-unstyled data-toggle='collapse' href="#js-collapse_#{project.id}" role='button' aria-expanded='false' aria-controls="js-collapse_#{project.id}"
        .card.btn.btn-outline-secondary.border-middle-purple.bg-light-purple.text-purple.button-text-wrap.height-150px
          .card-body.overflow-scroll
            .card-text.h4.mt-4
              = project.name

      .collapse.text-center id="js-collapse_#{project.id}"
        p.m-0
          = link_to 'プロジェクトを見る', project_path(project), class: 'btn btn-lg btn-outline-secondary border-middle-purple bg-light-purple text-purple mt-2'
        - if current_user.owner?(project)
          p.m-0
            = link_to 'プロジェクトの設定', edit_myproject_path(project), class: 'btn btn-lg btn-outline-secondary border-middle-purple bg-light-purple text-purple mt-2'

    - elsif current_user.member?(project)
      = link_to project_path(project), class: 'link-unstyled' do
        .card.btn.btn-outline-secondary.border-middle-purple.bg-light-purple.text-purple.button-text-wrap.height-150px
          .card-body.overflow-scroll
            .card-text.h4.mt-4
              = project.name

    - else
      .card.border-middle-purple.bg-white-purple.text-secondary-purple.height-150px
        .card-body.overflow-scroll
          .card-text.text-center.h4.mt-4
            = project.name

app/views/projects/_view_more.html.slim
.col-12.text-center
  = link_to_next_page projects, 'もっと見る', id: 'js-next_page_btn', class: 'btn btn-lg btn-outline-secondary border-middle-purple text-middle-purple mt-4 width-250px', remote: true

app/views/projects/index.html.slim
#js-projects.row
  = render 'projects', projects: @projects
#js-view_more
  = render 'view_more', projects: @projects

app/views/projects/index.js.erb
<%# サーバ側のビューテンプレートやkaminariのヘルパーメソッドを使いたいため、
    Server-generated Javascript Responseを使用する %>

<%# プロジェクト一覧に新しいプロジェクトを追加 %>
var projects = document.getElementById('js-projects');
var newProjects = "<%= j(render 'projects/projects', projects: @projects) %>";
projects.insertAdjacentHTML('beforeend', newProjects);

<%# 「もっと見る」ボタンを書き換え %>
var viewMore = document.getElementById('js-view_more');
var newViewMore = "<%= j(render 'projects/view_more', projects: @projects) %>";
viewMore.innerHTML = newViewMore;

app/views/projects/info.html.slim
.row
  .col-12.col-md-10.mx-auto.mt-4
    .card.border-middle-purple.text-purple
      .card-header.h3.bg-light-purple.pl-md-5 プロジェクト情報
      .card-body.p-md-5
        .card-text.h5
          .row.h4
            .col-auto = @project.name
          .row.h6.py-3.border-bottom
            .col-auto = simple_format(@project.summary)

          .row.mt-4.align-items-center.text-middle-purple
            - if @project.owner.image.attached?
              .col-auto = image_tag @project.owner.image, class: 'size35x35 rounded-circle'
            .col-5.col-md-4.col-lg-3.px-0.h4.mb-0 = @project.owner.name
            .col-auto.width-120px.text-center.font-weight-bold.ml-1.mt-1.mt-sm-0 オーナー
          
          - @project.members.each do |member|
            .row.mt-4.align-items-center.text-middle-purple
              - if member.image.attached?
                .col-auto = image_tag member.image, class: 'size35x35 rounded-circle'
              .col-5.col-md-4.col-lg-3.px-0.h4.mb-0 = member.name
              .col-auto.width-120px.text-center.ml-1.mt-1.mt-sm-0 メンバー

          = link_to project_path(@project), class: 'text-middle-purple link-unstyled float-right mt-5 mt-lg-0' do
            i.fas.fa-link.mr-1
            |プロジェクトに戻る

app/views/projects/show.html.slim
.row
  .col-xl-7.overflow-scroll
    .h4.text-middle-purple = @project.name

  .col-xl-5.text-right
    = link_to project_info_path(@project), class: 'btn btn-outline-secondary border-middle-purple text-middle-purple mr-1 width-100px' do
      i.fas.fa-info-circle.fa-lg.mr-1
      |情報
    = link_to project_logs_path(@project), class: 'btn btn-outline-secondary border-middle-purple text-middle-purple mr-1 width-100px' do
      i.far.fa-file-alt.fa-lg.mr-1
      |ログ
    - if current_user.owner?(@project)
      = link_to project_invite_path(@project), class: 'btn btn-outline-secondary border-middle-purple text-middle-purple width-100px' do
        i.fas.fa-user-friends.fa-lg.mr-1
        |招待

.row.mt-5.text-middle-purple.row-scroll-x.w-100.pb-2

  - @project.columns.each do |column|
    = render 'column', project: @project, column: column

  .col-2.col-scroll-x
    = link_to new_project_column_path(@project), class: 'btn btn-outline-secondary border-middle-purple bg-white-purple text-middle-purple mt-0' do
      i.fas.fa-plus-square.fa-lg.mr-2
      |カラムを追加