config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  # ログインページ
  controller :sessions do
    get 'login', action: :new
    get 'logout', action: :destroy
    get 'auth/:provider/callback', action: :create
  end

  # マイページ
  resource :mypage, controller: :users,
                    only: %i[show edit update destroy]

  # 全プロジェクト
  resources :projects, only: %i[index show] do
    resources :columns, only: %i[new create edit update destroy] do
      get 'previous', on: :member
      get 'next', on: :member
      resources :cards, only: %i[new create edit update destroy] do
        get 'previous', on: :member
        get 'next', on: :member
      end
    end

    # 招待
    controller :invitations do
      get 'invite', action: :invite
      get 'generate_invitaions', action: :generate_invitaions
      resources :invitations, only: %i[create]
    end

    # 参加
    resources :participations, only: %i[create]

    # 情報
    get 'info', to: 'projects#info'

    # ログ
    resources :logs, only: %i[index]
  end

  # マイプロジェクト
  resources :myprojects, controller: :projects, module: :myprojects,
                         only: %i[index new create edit update destroy]

  # お知らせ
  resources :notifications, only: %i[index]
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :columns, -> { order(position: :asc) }, dependent: :destroy
  has_many :cards, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :invitees, through: :invitations, source: :user
  has_many :participations, dependent: :destroy
  has_many :members, through: :participations, source: :user
  has_many :logs, dependent: :destroy
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id

  # プロジェクト一覧で1ページに表示するプロジェクトの個数
  COUNT_PER_PAGE = 9

  # プロジェクト一覧の先頭に挿入されるプロジェクト以外（リンクなど）の個数
  PADDING_COUNT = 1

  validates :name, presence: true, uniqueness: true, length: { maximum: 140 }
  validates :summary, length: { maximum: 300 }

  scope :for_full_list, ->(page) do
    order(id: :desc).page(page).per(COUNT_PER_PAGE)
  end

  scope :for_accessible_list, ->(user, page) do
    if page
      for_accessible_list_second_page_or_later(user, page)
    else
      for_accessible_list_first_page(user)
    end
  end

  scope :for_accessible_list_first_page, ->(user) do
    count_for_first_page = COUNT_PER_PAGE - PADDING_COUNT
    accessible(user).order(id: :desc).page(nil).per(count_for_first_page)
  end

  scope :for_accessible_list_second_page_or_later, ->(user, page) do
    # もし1ページ目が指定されても値を返さないようにする
    # （kaminariのissueによると、1ページ目でpaddingマイナス値を使うと不具合がある）
    return [] if ['1', 1, nil].include?(page)

    accessible(user).order(id: :desc).page(page).per(COUNT_PER_PAGE)
                    .padding(-PADDING_COUNT)
  end

  scope :accessible, ->(user) do
    owned_by(user).or(participated_in_by(user)).distinct
  end

  scope :owned_by, ->(user) do
    # .accessibleでorを使用できるようleft_joinsする
    left_joins(:participations).where(owner_id: user.id)
  end

  scope :participated_in_by, ->(user) do
    left_joins(:participations).where(participations: { user_id: user.id })
  end

  def accessible?(user)
    self.class.accessible(user).exists?(id)
  end

  def invite(user)
    invitations.build(user: user).save
  end

  def accessible_users
    [owner] + members
  end

  def set_owner!(new_owner)
    raise 'new_owner is not in members' unless members.exists?(new_owner.id)

    remove_member!(new_owner)
    update!(owner: new_owner)
  end

  def remove_member!(member)
    participations.find_by!(user: member).destroy!
  end

  def oldest_member
    members.order(created_at: :asc).first
  end
end

app/controllers/myprojects/projects_controller.rb
class Myprojects::ProjectsController < ApplicationController
  before_action :set_project, only: %i[edit update destroy]

  def index
    @projects = Project.for_accessible_list(current_user, params[:page])
    respond_to do |format|
      format.html
      format.js { render 'projects/index' }
    end
  end

  def new
    @project = current_user.owner_projects.build
  end

  def create
    @project = current_user.owner_projects.build(project_params)

    if @project.save
      redirect_to projects_path, notice: 'プロジェクトを作成しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path, notice: 'プロジェクトを更新しました'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy!
    redirect_to projects_path, notice: 'プロジェクトを削除しました'
  end

  private

  def project_params
    params.require(:project).permit(:name, :summary)
  end

  def set_project
    @project = current_user.owner_projects.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.for_full_list(params[:page])
  end

  def show
    @project = Project.accessible(current_user)
                      .includes(columns: :cards)
                      .find(params[:id])
  end

  def info
    @project = Project.accessible(current_user)
                      .includes(:owner)
                      .find(params[:project_id])
    @members = @project.members.order(id: :asc)
  end
end

app/views/myprojects/projects/_form.html.slim
.row
  .col-12.col-md-10.mx-auto.mt-4
    .card.border-middle-purple.text-purple
      .card-header.h3.bg-light-purple.pl-md-5 = title
      .card-body.p-md-5
        .card-text.h5
          = form_with model: project, url: project.form_path, local: true do |f|
            .form-group
              = f.label :name
              = f.text_field :name, class: field_class(model: project, field: :name)
              = render 'shared/form_errors', model: project, field: :name

            .form-group.mt-4
              = f.label :summary
              = f.text_area :summary, class: field_class(model: project, field: :summary), rows: '5'
              = render 'shared/form_errors', model: project, field: :summary

            - if project.new_record?
              = f.submit '作成', class: 'btn btn-lg btn-secondary bg-light-purple border-middle-purple text-middle-purple mt-4 width-200px'

            -else
              = f.submit '編集', class: 'btn btn-lg btn-secondary bg-light-purple border-middle-purple text-middle-purple mt-4 width-200px'
              = link_to '削除', myproject_path(project), method: :delete, data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-lg btn-outline-secondary border-middle-purple text-middle-purple mt-4 width-100px mt-4 ml-1 ml-sm-2'

          = link_to projects_path, class: 'text-middle-purple link-unstyled float-right mt-4 mt-lg-0' do
            i.fas.fa-link.mr-1
            |一覧に戻る

app/views/myprojects/projects/_new_project.html.slim
- if projects.first_page?
  .col-12.col-sm-6.col-lg-4.mt-4
    a.link-unstyled href="#{new_myproject_path}"
      .card.btn.btn-outline-secondary.border-middle-purple.text-purple.button-text-wrap.height-150px
        .card-body
          .card-text.h4.mt-4
            |プロジェクトを作成する

app/views/myprojects/projects/edit.html.slim
= render 'form', project: @project, title: 'プロジェクトを編集'

app/views/myprojects/projects/index.html.slim
#js-projects.row
  = render 'new_project', projects: @projects
  = render 'projects/projects', projects: @projects
#js-view_more
  = render 'projects/view_more', projects: @projects

app/views/myprojects/projects/new.html.slim
= render 'form', project: @project, title: 'プロジェクトを作成'